defaults:
    - agent: sac
    
# this needs to be specified manually
experiment: PEBBLE

# reward learning
segment: 50
activation: tanh
num_seed_steps: 1000
num_unsup_steps: 9000
num_interact: 10000
reward_lr: 0.0003
reward_batch: 50
reward_update: 10
feed_type: 0
reset_update: 100
topK: 5
ensemble_size: 3
max_feedback: 10000
large_batch: 10
label_margin: 0.0
teacher_beta: -1
teacher_gamma: 1
teacher_eps_mistake: 0
teacher_eps_skip: 0
teacher_eps_equal: 0

# scheduling
reward_schedule: 0

num_train_steps: 2e6
replay_buffer_capacity: ${num_train_steps}

# evaluation config
eval_frequency: 10000
num_eval_episodes: 10
device: cuda

# logger
log_frequency: 10000
log_save_tb: true

# video recorder
save_video: true

# setups
seed: 1

# Environment
# Kitchen
env: FrankaKitchen-v1
gradient_update: 1

# hydra configuration
hydra:
    name: ${env}
    run:
        dir: ./exp/FrankaKitchen-v1_sample${feed_type}/seed${seed}